//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import javax.swing.*;
 
public class GuiGenie extends JPanel {
    public static JFrame frame = new JFrame ("MyPanel");
    

    private JButton jcomp1;
    private JButton jcomp2;
    

    public GuiGenie() {
        //construct components
        jcomp1 = new JButton ("JPanel1");
        jcomp2 = new JButton ("JPanel2");

        //adjust size and set layout
        setPreferredSize (new Dimension (1080, 720));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (30, 110, 100, 25);
        jcomp2.setBounds (185, 105, 100, 25);

        jcomp1.addActionListener(e -> selectionButtonPressed1());
        jcomp2.addActionListener(e -> selectionButtonPressed2());
    }


    private Object selectionButtonPressed1() {
        System.out.println("Switch to 1");
        
        frame.getContentPane().removeAll();
        frame.getContentPane().add(new JPanel1());
        frame.setVisible (true);
        return null;
    }
    private Object selectionButtonPressed2() {
        System.out.println("Switch to 2");
        frame.getContentPane().removeAll();
        frame.getContentPane().add(new JPanel2());
        frame.setVisible (true);
        return null;
    }


    public static void main (String[] args) {
        
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new GuiGenie());
        frame.pack();
        frame.setVisible (true);


        
    }
}
