//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import javax.swing.*;

public class JPanel2 extends JPanel {
    private final JTextArea jcomp2;

    public JPanel2() {
        //construct components
        JButton btn_ExecSQL = new JButton("Execute SQL");
        jcomp2 = new JTextArea (5, 5);
        JButton btn_BackToMain = new JButton("Back");

        //adjust size and set layout
        setPreferredSize (new Dimension (1080, 720));
        setLayout (null);

        //add components
        add (btn_ExecSQL);
        add (jcomp2);
        add (btn_BackToMain);

        //set component bounds (only needed by Absolute Positioning)
        btn_ExecSQL.setBounds (780, 520, 150, 25);
        jcomp2.setBounds (5, 5, 930, 505);
        btn_BackToMain.setBounds (5, 525, 100, 25);

        btn_ExecSQL.addActionListener(e -> ExecuteSQL());
        btn_BackToMain.addActionListener(e -> BackToMain());
    }


    private void BackToMain() {
        JFrame bframe = GuiGenie.frame;
        bframe.getContentPane().removeAll();
        bframe.getContentPane().add(new GuiGenie());
        bframe.setVisible (true);
    }

    private void ExecuteSQL() {
        String query = jcomp2.getText();
        JPanel2_Exec.EXEC(query);
    }

    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new JPanel2());
        frame.pack();
        frame.setVisible (true);
    }
}
