//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import javax.swing.*;


public class JPanel1 extends JPanel {

    public JPanel1() {
        //construct preComponents
        String[] jcomp1Items = {"Test1", "AAA", "BBBB"};

        //construct components
        JList<String> jcomp1 = new JList<>(jcomp1Items);
        JButton jcomp2 = new JButton("Back");

        //set components properties
        jcomp1.setToolTipText ("Hmm");

        //adjust size and set layout
        setPreferredSize (new Dimension (944, 563));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (25, 235, 100, 75);
        jcomp2.setBounds (10, 10, 100, 25);
        
        jcomp2.addActionListener(e -> selectionButtonPressed());
    }


    private void selectionButtonPressed() {
        JFrame bframe = GuiGenie.frame;
        bframe.getContentPane().removeAll();
        bframe.getContentPane().add(new GuiGenie());
        bframe.setVisible (true);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MyPanel");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new JPanel1());
        frame.pack();
        frame.setVisible (true);
    }
}
