/*

Kelompok 1
Tanggal : 27 November 2022


-- Riwayat Versi.
1.3 | 5 Desember penambahan trigger
1.2 | 4 Desember 2022 Normalisasi + New Entity.
1.1 | 27 November 2022 (IdMapel 5 nvarchar -> 8 nvarchar, tambah drop table lainnya)
1.0 | 27 November 2022
*/

USE SMP;
DROP TABLE IF EXISTS ORGANISASI;
DROP TABLE IF EXISTS EKSTRAKURIKULER;
DROP TABLE IF EXISTS PARTISIPASI_NONAKADEMIK;
DROP TABLE IF EXISTS KEGIATAN_NONAKADEMIK;
DROP TABLE IF EXISTS PARTISIPASI_LOMBA;
DROP TABLE IF EXISTS PERLOMBAAN;
DROP TABLE IF EXISTS MENGAJAR_MAPEL;
DROP TABLE IF EXISTS NILAI_UH;
DROP TABLE IF EXISTS NILAI_TUGAS;
DROP TABLE IF EXISTS DATA_NILAI;
DROP TABLE IF EXISTS DATA_PRESENSI;
DROP TABLE IF EXISTS KONSELING;
DROP TABLE IF EXISTS SISWA_AKTIF
DROP TABLE IF EXISTS SISWA_KELUAR
DROP TABLE IF EXISTS SISWA_LULUS
DROP TABLE IF EXISTS SISWA;
DROP TABLE IF EXISTS WALI_MURID;
DROP TABLE IF EXISTS KELAS;
DROP TABLE IF EXISTS MAPEL;
DROP TABLE IF EXISTS GURU;

CREATE TABLE GURU (
	NIK NVARCHAR(16) NOT NULL,
	Nama NVARCHAR(64),
	JenisKelamin NVARCHAR(1),
	Agama NVARCHAR(10),
	Jabatan NVARCHAR(32),
	Alamat NVARCHAR(128),
	TanggalLahir DATE,

	
    CONSTRAINT PK_Guru PRIMARY KEY (NIK)
);

CREATE TABLE MAPEL (
	IdMapel INTEGER NOT NULL,
	NamaMapel NVARCHAR(64) NOT NULL,
	
    CONSTRAINT PK_Mapel PRIMARY KEY (IdMapel)
);

CREATE TABLE KELAS (
	IdKelas INTEGER NOT NULL,
	NamaKelas NVARCHAR(4),
	Tingkat TINYINT,
	NIK_Wali NVARCHAR(16),
	
	
    CONSTRAINT PK_Kelas PRIMARY KEY (IdKelas),

	CONSTRAINT FK_Kelas_Wali FOREIGN KEY (NIK_Wali)
	REFERENCES GURU(NIK)
);

CREATE TABLE WALI_MURID (
	NIK NVARCHAR(16) NOT NULL,
	Nama NVARCHAR(64),
	Pekerjaan NVARCHAR(32)

	CONSTRAINT PK_WaliMurid PRIMARY KEY (NIK)
);

CREATE TABLE SISWA (
	NIS INTEGER NOT NULL,
	Nama NVARCHAR(64) NOT NULL,
	TanggalLahir DATE,
	KotaLahir NVARCHAR(32),
	Alamat NVARCHAR(128),
	Agama NVARCHAR(10),
	JenisKelamin NVARCHAR(1),
	TanggalMasuk DATE,
	
	

	CONSTRAINT PK_Siswa PRIMARY KEY (NIS),
);

CREATE TABLE SISWA_AKTIF (
	NIS INTEGER NOT NULL,
	FK_IdKelas INTEGER NOT NULL,
	FK_NIKWaliMurid NVARCHAR(16) NOT NULL,

	CONSTRAINT FK_SiswaAktif_Siswa FOREIGN KEY(NIS)
	REFERENCES SISWA(NIS),

	CONSTRAINT FK_Siswa_Kelas FOREIGN KEY (FK_IdKelas)
	REFERENCES KELAS(IdKelas),

	CONSTRAINT FK_Siswa_Ortu FOREIGN KEY (FK_NIKWaliMurid)
	REFERENCES WALI_MURID(NIK),
);

CREATE TABLE SISWA_LULUS (
	NIS INTEGER NOT NULL,
	TanggalLulus DATE,

	CONSTRAINT FK_SiswaLulus_Siswa FOREIGN KEY(NIS)
	REFERENCES SISWA(NIS),
);

CREATE TABLE SISWA_KELUAR (
	NIS INTEGER NOT NULL,
	TanggalKeluar DATE,
	

	CONSTRAINT FK_SiswaKeluar_Siswa FOREIGN KEY(NIS)
	REFERENCES SISWA(NIS),
);

CREATE TABLE KONSELING (
	NIS INTEGER NOT NULL,
	FK_NIKBK NVARCHAR(16),
	MinatBakat NVARCHAR(64),

	CONSTRAINT FK_Konseling_Siswa FOREIGN KEY(NIS)
	REFERENCES SISWA(NIS),
	CONSTRAINT FK_Konseling_Guru FOREIGN KEY(FK_NIKBK)
	REFERENCES GURU(NIK)

);

CREATE TABLE DATA_PRESENSI (
	IdPresensi INTEGER NOT NULL,
	Semester TINYINT NOT NULL,
	Kehadiran NVARCHAR(6) NOT NULL,
	FK_NIS INTEGER NOT NULL,

	CONSTRAINT PK_DataPresensi PRIMARY KEY (IdPresensi),

	CONSTRAINT FK_Presensi_Siswa FOREIGN KEY (FK_NIS)
	REFERENCES SISWA(NIS),
);

CREATE TABLE DATA_NILAI (
	IdNilai INTEGER NOT NULL,
	Semester TINYINT NOT NULL,
	UTS DECIMAL(5,2),
	UAS DECIMAL(5,2),
	NilaiAkhirMapelDiSmt DECIMAL(5,2),
	FK_NIS INTEGER NOT NULL,
	FK_Mapel INTEGER NOT NULL,


	CONSTRAINT PK_DataNilai PRIMARY KEY (IdNilai),

	CONSTRAINT FK_DataNilai_Siswa FOREIGN KEY (FK_NIS)
	REFERENCES SISWA(NIS),

	CONSTRAINT FK_DataNilai_Mapel FOREIGN KEY (FK_Mapel)
	REFERENCES MAPEL(IdMapel)

);

CREATE TABLE NILAI_UH(
	IdNilaiUH INTEGER NOT NULL,
	UH_Ke TINYINT,
	Nilai DEC(5,2),
	FK_DataNilai INTEGER NOT NULL,

	CONSTRAINT PK_NilaiUH PRIMARY KEY(IdNilaiUH),

	CONSTRAINT FK_NilaiUH_DataNilai FOREIGN KEY(FK_DataNilai)
	REFERENCES Data_Nilai(IdNilai)
);

CREATE TABLE NILAI_TUGAS(
	IdNilaiTugas INTEGER NOT NULL,
	Tugas_Ke TINYINT,
	Nilai DEC(5,2),
	FK_DataNilai INTEGER NOT NULL,

	CONSTRAINT PK_NilaiTugas PRIMARY KEY(IdNilaiTugas),

	CONSTRAINT FK_NilaiTugas_DataNilai FOREIGN KEY(FK_DataNilai)
	REFERENCES Data_Nilai(IdNilai)
);



CREATE TABLE KEGIATAN_NONAKADEMIK(
	IdKegiatan INTEGER NOT NULL,
	NamaKegiatan NVARCHAR(32),
	FK_NIKPembina NVARCHAR(16) NOT NULL,

	CONSTRAINT PK_KegiatanNonAkademik PRIMARY KEY (IdKegiatan),

	CONSTRAINT FK_KegiatanNonAkademik_Guru FOREIGN KEY (FK_NIKPembina)
	REFERENCES GURU(NIK)
);

CREATE TABLE PERLOMBAAN(
	IdLomba INTEGER NOT NULL,
	NamaLomba NVARCHAR(32),
	JenisLomba NVARCHAR(24),
	Tingkatan NVARCHAR(24),
	KetPartisipasi NVARCHAR(16),
	TglMulai DATE,
	TglSelesai DATE,
	FK_NIKPembina NVARCHAR(16) NOT NULL, 

	CONSTRAINT PK_Perlombaan PRIMARY KEY (IdLomba),
	CONSTRAINT FK_Perlombaan_Guru FOREIGN KEY (FK_NIKPembina)
	REFERENCES GURU(NIK)
);
 --- relations
CREATE TABLE PARTISIPASI_LOMBA(
	IdLomba INTEGER NOT NULL,
	NIS_Siswa INTEGER NOT NULL,
	


	CONSTRAINT FK_PartisipasiLomba_Siswa FOREIGN KEY (NIS_Siswa)
	REFERENCES SISWA(NIS),

	CONSTRAINT FK_PartisipasiLomba_Perlombaan FOREIGN KEY (IdLomba)
	REFERENCES PERLOMBAAN(IdLomba)

);

CREATE TABLE PARTISIPASI_NONAKADEMIK (
	IdKegiatan INTEGER NOT NULL,
	NIS_Siswa INTEGER NOT NULL,
	


	CONSTRAINT FK_PartisipasiNonAkademik_Siswa FOREIGN KEY (NIS_Siswa)
	REFERENCES SISWA(NIS),

	CONSTRAINT FK_PartisipasiNonAkademik_KegiatanNonAkademik FOREIGN KEY (IdKegiatan)
	REFERENCES KEGIATAN_NONAKADEMIK(IdKegiatan)
);

CREATE TABLE MENGAJAR_MAPEL(
	NIK_Guru NVARCHAR(16) NOT NULL ,
	IdMapel INTEGER NOT NULL,


	CONSTRAINT FK_MengajarMapel_Guru FOREIGN KEY (NIK_Guru)
	REFERENCES GURU(NIK),

	CONSTRAINT FK_MengajarMapel_Mapel FOREIGN KEY (IdMapel)
	REFERENCES MAPEL(IdMapel)
);


 --- superclass -> subclass
CREATE TABLE EKSTRAKURIKULER (
	IdKegiatan INTEGER NOT NULL,
	MinatBakat NVARCHAR(15),

	CONSTRAINT FK_Ekstrakurikuler_KegiatanNonAkademik FOREIGN KEY (IdKegiatan)
	REFERENCES KEGIATAN_NONAKADEMIK(IdKegiatan)
);

CREATE TABLE ORGANISASI (
	IdKegiatan INTEGER NOT NULL,
	Proker NTEXT,

	CONSTRAINT FK_Organisasi_KegiatanNonAkademik FOREIGN KEY (IdKegiatan)
	REFERENCES KEGIATAN_NONAKADEMIK(IdKegiatan)
);